name: Run Python Script Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Cada día a la medianoche UTC
  workflow_dispatch:    # Permite ejecutarlo manualmente también

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install system dependencies for Pillow
        run: |
          sudo apt-get update
          sudo apt-get install -y libjpeg-dev zlib1g-dev libfreetype6-dev

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install Pillow==9.5.0 moviepy
      - name: Instalar FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py

