name: Run Python Script Daily
on:
  schedule:
    - cron: '0 0 * * *'  # Cada día a la medianoche UTC
  workflow_dispatch:    # Permite ejecutarlo manualmente también
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Instalar dependencias del sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick libmagickwand-dev
        convert -version  # Verifica que se instaló bien
        
    - name: Configurar política de seguridad de ImageMagick (evitar errores de seguridad)
      run: |
        sudo sed -i 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml || true
        sudo sed -i 's/rights="none" pattern="LABEL"/rights="read|write" pattern="LABEL"/' /etc/ImageMagick-6/policy.xml || true
        
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libjpeg-dev zlib1g-dev libfreetype6-dev libsndfile1-dev ffmpeg espeak-ng
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        # Instalar PyTorch primero para evitar conflictos
        pip install torch==2.0.0 --extra-index-url https://download.pytorch.org/whl/cpu
        pip install -r requirements.txt
        pip install --upgrade moviepy google-auth google-auth-oauthlib google-api-python-client
        
    - name: Run script
      run: python main.py
